<?php
// Auto-generated by generate_uintas_dashboard.py
// Reruns the weather dashboard generator and redirects back to the dashboard.
$python = '/bin/python3';
$script = '/home2/vofgesmy/python/scripts/generate_uintas_dashboard.py';
$output = __DIR__ . '/Uintas-Weather-Stations.html';
$cmd    = $python . " " . escapeshellarg($script) . " --output " . escapeshellarg($output) . " 2>&1";
shell_exec($cmd);
header('Location: Uintas-Weather-Stations.html');
exit;
