<?php
// Auto-generated by generate_skyline_dashboard.py
// Reruns the weather dashboard generator and redirects back to the dashboard.
$python = '/bin/python3';
$script = 'generate_skyline_dashboard.py';
$output = __DIR__ . '/Skyline-Weather-Stations.html';
$cmd    = $python . " " . escapeshellarg($script) . " --output " . escapeshellarg($output) . " 2>&1";
shell_exec($cmd);
header('Cache-Control: no-store, no-cache, must-revalidate');
header('Pragma: no-cache');
header('Location: Skyline-Weather-Stations.html?t=' . time());
exit;
